### ISSUE TITLE
Yolov9 export to onnx

### ISSUE THREAD

**Issue by FelixSandmair** [WeiZhenOoooo/yolov9-onnx-opencv#1]
I have a question regarding the export of the yolov9 model. I have pulled the https://github.com/WongKinYiu/yolov9.git github and used the export.py for the exportation like this:

python3 export.py --weights yolov9-s-converted.pt --imgsz 640 --include onnx

When i use this model for object detection the confidences seem meaning in an empty picture with a person I get multiple person detections. The x, y, width and height values on the other hand are not correct (all 0s). Do you know if this has something to do with how I export the model. 

Kind regards
Felix Sandmair

**Comment by WeiZhenOoooo** [comment]
![QQ截图20240923093816](https://github.com/user-attachments/assets/dc712321-f58e-418b-a3f9-27687065cd55)
Hi, I tried it myself and didn't find the problem you mentioned. Could you give more details?

**Comment by FelixSandmair** [comment]
Hi, Thanks first for answering me. I found out that the problem has something to do with running it on GPU. When running it on my Nvidia graphics card with cuda I get this issue with alle zeros for the Positon values but correct confidences and when running it on CPU everything is correct. So I guess its something with driver versions and OpenCV Version.
